// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "StationSystemsComponent.generated.h"

class AStationModule;
class AStationGrid;

DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnSystemStateChanged);

/**
 * Station-wide system simulation component.
 * Manages power distribution, oxygen/atmosphere propagation, and resource tracking.
 * Attached to the GameMode actor.
 */
UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class UStationSystemsComponent : public UActorComponent
{
	GENERATED_BODY()

public:

	UStationSystemsComponent();

	// Power System

	/** Total power being generated by all modules */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Power")
	int32 TotalPowerGeneration = 0;

	/** Total power being consumed by all modules */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Power")
	int32 TotalPowerConsumption = 0;

	/** Is the station generating enough power for all modules */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Power")
	bool bHasSufficientPower = false;

	// Oxygen System

	/** Total oxygen being generated by all modules */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Oxygen")
	int32 TotalOxygenGeneration = 0;

	/** Total oxygen being consumed by all modules */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Oxygen")
	int32 TotalOxygenConsumption = 0;

	/** Is the station generating enough oxygen */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Oxygen")
	bool bHasSufficientOxygen = false;

public:

	/** Tick station systems (called from GameMode::Tick) */
	void TickSystems(float DeltaSeconds);

	/** Recalculate all resource totals from module registry */
	UFUNCTION(BlueprintCallable, Category="Systems")
	void RecalculateResources();

	/** Update power state on all modules */
	UFUNCTION(BlueprintCallable, Category="Systems")
	void UpdatePowerDistribution();

	/** Propagate atmosphere through connected modules from life support */
	UFUNCTION(BlueprintCallable, Category="Systems")
	void PropagateAtmosphere();

	/** Check if station has sufficient power */
	UFUNCTION(BlueprintPure, Category="Systems")
	bool IsPowerSufficient() const { return bHasSufficientPower; }

	/** Check if station has sufficient oxygen */
	UFUNCTION(BlueprintPure, Category="Systems")
	bool IsOxygenSufficient() const { return bHasSufficientOxygen; }

	/** Get net power (generation - consumption) */
	UFUNCTION(BlueprintPure, Category="Systems")
	int32 GetNetPower() const { return TotalPowerGeneration - TotalPowerConsumption; }

	/** Get net oxygen (generation - consumption) */
	UFUNCTION(BlueprintPure, Category="Systems")
	int32 GetNetOxygen() const { return TotalOxygenGeneration - TotalOxygenConsumption; }

	// Blueprint Events

	/** Called when power state changes (sufficient/insufficient) */
	UPROPERTY(BlueprintAssignable, Category="Systems")
	FOnSystemStateChanged OnPowerStateChanged;

	/** Called when oxygen state changes (sufficient/insufficient) */
	UPROPERTY(BlueprintAssignable, Category="Systems")
	FOnSystemStateChanged OnOxygenStateChanged;

private:

	/** Timer for periodic system updates */
	float SystemUpdateTimer = 0.0f;

	/** How often to recalculate systems (seconds) */
	UPROPERTY(EditAnywhere, Category="Systems")
	float SystemUpdateInterval = 0.5f;

	/** Helper: Get all modules from GameMode */
	TArray<AStationModule*> GetAllModules() const;

	/** Helper: Get station grid from GameMode */
	AStationGrid* GetStationGrid() const;

	/** Flood-fill atmosphere from a starting module */
	void FloodFillAtmosphere(AStationModule* StartModule, TSet<AStationModule*>& VisitedModules);
};
